apiVersion: v1
kind: Service
metadata:
  name: exam-study-app-nodeport
  namespace: exam-study-prod
spec:
  selector:
    app: exam-study-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
