apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterissuer.yaml
  - certificate.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - referencegrants.yaml
  - httproutes.yaml
